// 定义天气时钟全局运行状态、版本信息和跨模块共享对象。
#include "app_state.h"

const char *const TAG = "WeatherClock";
const char *const APP_VERSION = "v1.4.38";
#ifndef WEATHER_CLOCK_BUILD_DATE
#define WEATHER_CLOCK_BUILD_DATE "unknown"
#endif
const char *const APP_BUILD_DATE = WEATHER_CLOCK_BUILD_DATE;
DisplayPort g_display(12, 11, 5, 40, 41, kDisplayWidth, kDisplayHeight);
I2cMasterBus g_i2c(14, 13, 0);
Shtc3Port *g_shtc3 = nullptr;
CodecPort *g_codec = nullptr;
portMUX_TYPE g_audio_state_mux = portMUX_INITIALIZER_UNLOCKED;
portMUX_TYPE g_weather_state_mux = portMUX_INITIALIZER_UNLOCKED;
bool g_audio_playing = false;
volatile bool g_startup_screen_active = true;
volatile bool g_setup_prompt_pending = false;
#if CONFIG_PM_ENABLE
esp_pm_lock_handle_t g_network_pm_lock = nullptr;
esp_pm_lock_handle_t g_audio_pm_lock = nullptr;
int g_network_pm_lock_depth = 0;
int g_audio_pm_lock_depth = 0;
#endif
adc_oneshot_unit_handle_t g_battery_adc = nullptr;
adc_cali_handle_t g_battery_adc_cali = nullptr;
bool g_battery_adc_ready = false;
bool g_battery_adc_cali_ready = false;
EventGroupHandle_t g_app_events;
httpd_handle_t g_http_server = nullptr;
char g_wifi_ssid[33] = {};
char g_wifi_pass[65] = {};
char g_weather_api_key[96] = {};
char g_manual_weather_city[kManualWeatherCityLen] = {};
char g_ap_ssid[33] = {};
char g_sta_ip[16] = {};
bool g_have_wifi_creds = false;
bool g_have_weather_key = false;
bool g_has_manual_weather_city = false;
bool g_hourly_chime_enabled = false;
bool g_hourly_chime_all_day = false;
bool g_offline_mode_ui_enabled = false;
int g_chime_volume_percent = 80;
int g_chime_sound_index = 0;
bool g_ntp_started = false;
bool g_wifi_radio_on = false;
bool g_wifi_stop_requested = false;
bool g_setup_portal_active = false;
int g_last_wifi_disconnect_reason = 0;
int g_http_timeout_ms = kHttpDefaultTimeoutMs;
int64_t g_boot_sync_deadline_us = 0;
float g_temperature = 0.0f;
float g_humidity = 0.0f;
bool g_sensor_ok = false;
int g_temp_trend = 0;
int g_humi_trend = 0;
int g_battery_percent = -1;
float g_battery_voltage = -1.0f;
bool g_battery_charging = false;
uint32_t g_battery_version = 0;
time_t g_last_ntp_sync_time = 0;
time_t g_last_weather_sync_time = 0;
volatile bool g_boot_info_requested = false;
volatile bool g_network_diag_page_requested = false;
volatile bool g_settings_requested = false;
volatile bool g_settings_focus_secondary = false;
volatile bool g_settings_page_order_mode = false;
volatile int g_settings_primary_selection = kSettingsPrimaryNetwork;
volatile int g_settings_selection = 0;
volatile int g_settings_page_order_selection = 0;
volatile uint32_t g_settings_action_seq = 0;
volatile TickType_t g_settings_last_activity_tick = 0;
volatile int g_settings_sync_op = kSettingsSyncNone;
volatile TickType_t g_settings_sync_deadline_tick = 0;
volatile TickType_t g_info_page_until_tick = 0;
TickType_t g_settings_feedback_until_tick = 0;
bool g_factory_reset_confirm_pending = false;
bool g_offline_disable_confirm_pending = false;
bool g_weather_city_clear_confirm_pending = false;
char g_settings_feedback[48] = {};
volatile int g_ota_state = kOtaIdle;
volatile int g_ota_progress = -1;
volatile int g_ota_speed_kbps = -1;
volatile TickType_t g_ota_status_until_tick = 0;
char g_ota_status[kOtaStatusLen] = "BOOT: Check Update";
char g_ota_version[kOtaVersionLen] = {};
char g_ota_url[kOtaUrlLen] = {};
char g_ota_sha256[kOtaSha256Len] = {};
char g_ota_notes[kOtaNotesLen] = {};
int g_ota_size = 0;
volatile int g_network_diag_state = kNetworkDiagIdle;
volatile int g_network_diag_step = 0;
volatile int g_network_diag_passed = 0;
volatile int g_network_diag_total = 0;
char g_network_diag_lines[kNetworkDiagLineCount][kNetworkDiagLineLen] = {};
char g_daily_saying[kDailySayingLen] = {};
time_t g_last_saying_sync_time = 0;
WeatherData g_weather;
WeatherAlertData g_weather_alert;
WeatherForecastData g_weather_forecast;
WeatherAirData g_weather_air;
volatile bool g_low_battery_mode = false;
SensorSample g_sensor_history[kSensorHistoryMinutes];
int g_sensor_history_next = 0;
int g_sensor_history_count = 0;
bool g_sensor_average_valid = false;
float g_last_temp_average = 0.0f;
float g_last_humi_average = 0.0f;
HourlySensorHistoryBlob g_hourly_history;
int64_t g_last_hourly_saved_at = 0;
uint32_t g_hourly_history_version = 0;
volatile int g_active_work_page = 0;
uint8_t g_work_page_enabled_mask = (uint8_t)((1U << kWorkPageCount) - 1);
uint8_t g_work_page_order[kWorkPageCount] = {
    kWorkPageWeatherClock,
    kWorkPageFlipClock,
    kWorkPageGallery,
    kWorkPageHistory,
    kWorkPageCalendar,
    kWorkPageWeatherBoard,
};
lv_obj_t *g_clock_root;
lv_obj_t *g_history_root;
lv_obj_t *g_gallery_root;
lv_obj_t *g_calendar_root;
lv_obj_t *g_weather_board_root;
lv_obj_t *g_flip_clock_root;
lv_obj_t *g_info_root;
lv_obj_t *g_network_diag_root;
lv_obj_t *g_settings_root;
lv_obj_t *g_date_label;
lv_obj_t *g_clock_summary_label;
lv_obj_t *g_history_date_label;
lv_obj_t *g_gallery_date_label;
lv_obj_t *g_calendar_date_label;
lv_obj_t *g_weather_board_date_label;
lv_obj_t *g_flip_clock_date_label;
lv_obj_t *g_history_summary_label;
lv_obj_t *g_gallery_summary_label;
lv_obj_t *g_calendar_summary_label;
lv_obj_t *g_weather_board_summary_label;
lv_obj_t *g_flip_clock_summary_label;
lv_obj_t *g_history_status_time_label;
lv_obj_t *g_gallery_status_time_label;
lv_obj_t *g_calendar_status_time_label;
lv_obj_t *g_weather_board_status_time_label;
lv_obj_t *g_flip_clock_status_time_label;
lv_obj_t *g_work_status_chime_icon_canvas[kWorkPageCount];
lv_color_t *g_work_status_chime_icon_canvas_buf[kWorkPageCount];
lv_obj_t *g_work_status_wifi_icon_canvas[kWorkPageCount];
lv_color_t *g_work_status_wifi_icon_canvas_buf[kWorkPageCount];
lv_obj_t *g_gallery_time_label;
lv_obj_t *g_gallery_hour_label;
lv_obj_t *g_gallery_minute_label;
lv_obj_t *g_gallery_image_canvas;
lv_color_t *g_gallery_image_canvas_buf;
lv_obj_t *g_gallery_time_canvas;
lv_color_t *g_gallery_time_canvas_buf;
lv_obj_t *g_gallery_saying_label;
lv_obj_t *g_temp_icon_canvas;
lv_obj_t *g_humi_icon_canvas;
lv_color_t *g_temp_icon_canvas_buf;
lv_color_t *g_humi_icon_canvas_buf;
lv_obj_t *g_temp_label;
lv_obj_t *g_humi_label;
lv_obj_t *g_temp_trend_canvas;
lv_obj_t *g_humi_trend_canvas;
lv_color_t *g_temp_trend_canvas_buf;
lv_color_t *g_humi_trend_canvas_buf;
lv_obj_t *g_weather_city_label;
lv_obj_t *g_weather_info_label;
lv_obj_t *g_weather_icon_label;
lv_obj_t *g_weather_temp_label;
lv_obj_t *g_weather_humi_label;
lv_obj_t *g_alert_pill;
lv_obj_t *g_alert_icon_canvas;
lv_color_t *g_alert_icon_canvas_buf;
lv_obj_t *g_alert_label;
lv_obj_t *g_chime_status_icon_canvas;
lv_color_t *g_chime_status_icon_canvas_buf;
lv_obj_t *g_wifi_status_icon_canvas;
lv_color_t *g_wifi_status_icon_canvas_buf;
lv_obj_t *g_low_battery_icon_canvas;
lv_color_t *g_low_battery_icon_canvas_buf;
lv_obj_t *g_panel_sep_a;
lv_obj_t *g_panel_sep_b;
lv_obj_t *g_battery_segments[5];
lv_obj_t *g_history_battery_segments[5];
lv_obj_t *g_gallery_battery_segments[5];
lv_obj_t *g_calendar_battery_segments[5];
lv_obj_t *g_weather_board_battery_segments[5];
lv_obj_t *g_flip_clock_battery_segments[5];
lv_obj_t *g_calendar_month_label;
lv_obj_t *g_calendar_canvas;
lv_color_t *g_calendar_canvas_buf;
lv_obj_t *g_history_chart_canvas;
lv_color_t *g_history_chart_canvas_buf;
lv_obj_t *g_history_temp_max_label;
lv_obj_t *g_history_temp_min_label;
lv_obj_t *g_history_humi_max_label;
lv_obj_t *g_history_humi_min_label;
lv_obj_t *g_history_time_labels[5];
lv_obj_t *g_history_temp_axis_labels[3];
lv_obj_t *g_history_humi_axis_labels[3];
lv_obj_t *g_time_canvas;
lv_color_t *g_time_canvas_buf;
lv_obj_t *g_second_canvas;
lv_color_t *g_second_canvas_buf;
lv_obj_t *g_status_gif_canvas;
lv_color_t *g_status_gif_canvas_buf;
lv_obj_t *g_day_progress_canvas;
lv_color_t *g_day_progress_canvas_buf;
lv_obj_t *g_second_progress_canvas;
lv_color_t *g_second_progress_canvas_buf;
lv_obj_t *g_flip_clock_card_canvas[3];
lv_color_t *g_flip_clock_card_canvas_buf[3];
lv_obj_t *g_flip_clock_sensor_label;
lv_obj_t *g_flip_clock_day_progress_canvas;
lv_color_t *g_flip_clock_day_progress_canvas_buf;
lv_obj_t *g_flip_clock_second_progress_canvas;
lv_color_t *g_flip_clock_second_progress_canvas_buf;
lv_obj_t *g_lower_panel_objects[13];
lv_obj_t *g_setup_status_labels[6];
lv_obj_t *g_boot_status_label;
lv_obj_t *g_boot_detail_label;
lv_obj_t *g_boot_anim_canvas;
lv_color_t *g_boot_anim_canvas_buf;
lv_obj_t *g_info_labels[5];
lv_obj_t *g_network_diag_labels[kNetworkDiagLineCount];
lv_obj_t *g_network_diag_summary_label;
lv_obj_t *g_network_diag_hint_label;
lv_obj_t *g_info_ota_label;
lv_obj_t *g_info_ota_hint_label;
lv_obj_t *g_info_ota_bar_frame;
lv_obj_t *g_info_ota_bar_fill;
lv_obj_t *g_settings_labels[kSettingsLabelCount];
lv_obj_t *g_settings_switch_dots[kSettingsSecondaryMaxCount];
lv_obj_t *g_settings_switch_texts[kSettingsSecondaryMaxCount];
lv_obj_t *g_settings_feedback_label;
lv_obj_t *g_settings_ota_status_label;
lv_obj_t *g_settings_ota_hint_label;
lv_obj_t *g_settings_ota_bar_frame;
lv_obj_t *g_settings_ota_bar_fill;
volatile bool g_boot_anim_running = false;
volatile int g_boot_anim_current_frame = 0;
TaskHandle_t g_boot_anim_task_handle = nullptr;
TaskHandle_t g_boot_sync_task_handle = nullptr;
TaskHandle_t g_ui_task_handle = nullptr;
int g_last_ui_second = -1;
int g_last_ui_minute = -1;
int g_last_ui_date_key = -1;
int g_last_ui_date_page = -1;
int g_last_day_progress_filled = -1;
int g_last_second_progress_filled = -1;
int g_last_status_gif_frame = -1;
int g_last_flip_clock_hour = -1;
int g_last_flip_clock_minute = -1;
int g_last_flip_clock_second = -1;
int g_last_flip_day_progress_filled = -1;
int g_last_flip_second_progress_filled = -1;
int g_last_flip_sensor_minute = -1;
int g_last_temp_trend_drawn = 99;
int g_last_humi_trend_drawn = 99;
uint32_t g_last_history_drawn_version = (uint32_t)-1;
int g_last_history_drawn_hour = -1;
int g_last_calendar_drawn_month = -1;
int g_last_calendar_drawn_day = -1;
