#!/usr/bin/env python3
from pathlib import Path

from PIL import Image, ImageEnhance, ImageOps


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/gif_video/1ae6a4ce-ab48-4d73-bf3c-1822291d84c4.gif"
HEADER = ROOT / "RLCD_CLOCK/main/status_gif_60.h"
PREVIEW = ROOT / "RLCD_CLOCK/simulator/status_gif_preview.png"

FRAME_COUNT = 60
SIZE = 84


def render_frame(image: Image.Image, index: int) -> Image.Image:
    image.seek(index)
    frame = image.convert("RGBA")
    frame.thumbnail((SIZE, SIZE), Image.Resampling.LANCZOS)

    canvas = Image.new("RGBA", (SIZE, SIZE), (255, 255, 255, 255))
    canvas.alpha_composite(frame, ((SIZE - frame.width) // 2, (SIZE - frame.height) // 2))

    rgb = canvas.convert("RGB")
    gray = Image.new("L", (SIZE, SIZE), 255)
    src = rgb.load()
    dst = gray.load()
    for y in range(SIZE):
        for x in range(SIZE):
            r, g, b = src[x, y]
            if r > 245 and g > 245 and b > 245:
                value = 255
            elif max(r, g, b) < 75:
                value = 0
            elif r > 120 and g < 95 and b < 120:
                value = 35
            elif b > 100 and g > 80 and r < 110:
                value = 205
            elif r > 150 and g > 90 and b < 120:
                value = 155
            else:
                value = int(0.299 * r + 0.587 * g + 0.114 * b)
            dst[x, y] = value

    gray = ImageOps.autocontrast(gray, cutoff=1)
    gray = ImageEnhance.Contrast(gray).enhance(1.15)
    gray = ImageEnhance.Brightness(gray).enhance(1.04)
    return gray.convert("1", dither=Image.Dither.FLOYDSTEINBERG)


def pack_bits(frame: Image.Image) -> list[int]:
    data = []
    byte = 0
    bit_count = 0
    for px in frame.getdata():
        black = px == 0
        byte = (byte << 1) | (1 if black else 0)
        bit_count += 1
        if bit_count == 8:
            data.append(byte)
            byte = 0
            bit_count = 0
    if bit_count:
        data.append(byte << (8 - bit_count))
    return data


def write_preview(frames: list[Image.Image]) -> None:
    cols = 10
    rows = (len(frames) + cols - 1) // cols
    sheet = Image.new("1", (cols * SIZE, rows * SIZE), 1)
    for i, frame in enumerate(frames):
        sheet.paste(frame, ((i % cols) * SIZE, (i // cols) * SIZE))
    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    sheet.convert("RGB").save(PREVIEW)


def main() -> None:
    image = Image.open(SOURCE)
    indices = [round(i * (image.n_frames - 1) / (FRAME_COUNT - 1)) for i in range(FRAME_COUNT)]
    frames = [render_frame(image, index) for index in indices]
    packed = [pack_bits(frame) for frame in frames]
    bytes_per_frame = len(packed[0])

    with HEADER.open("w") as out:
        out.write("#pragma once\n\n")
        out.write("// Generated by scripts/generate_status_gif.py.\n")
        out.write("// Source: assets/gif_video/1ae6a4ce-ab48-4d73-bf3c-1822291d84c4.gif\n")
        out.write("// 60 evenly sampled monochrome dithered frames for the main screen status panel.\n")
        out.write("#include <stdint.h>\n\n")
        out.write(f"static constexpr int STATUS_GIF_WIDTH = {SIZE};\n")
        out.write(f"static constexpr int STATUS_GIF_HEIGHT = {SIZE};\n")
        out.write(f"static constexpr int STATUS_GIF_FRAME_COUNT = {FRAME_COUNT};\n")
        out.write(f"static constexpr int STATUS_GIF_BYTES_PER_FRAME = {bytes_per_frame};\n\n")
        out.write("static const uint8_t status_gif_frames[STATUS_GIF_FRAME_COUNT][STATUS_GIF_BYTES_PER_FRAME] = {\n")
        for i, frame in enumerate(packed):
            out.write(f"    {{ // frame {i}\n        ")
            for j, byte in enumerate(frame):
                if j and j % 16 == 0:
                    out.write("\n        ")
                out.write(f"0x{byte:02X}, ")
            out.write("\n    },\n")
        out.write("};\n")

    write_preview(frames)
    print(f"Wrote {HEADER}")
    print(f"Wrote {PREVIEW}")


if __name__ == "__main__":
    main()
